version: "3.9"

services:

  app:
    build: 
      context: .
      dockerfile: ./.docker/Dockerfile 
      target: production
    ports:
      - 80:80

  preview: 
    image: ghcr.io/andrejvysny/react-template:latest
    ports:
      - 80:80
    environment:
      - VITE_TITLE="value"