name: CI

on:
  workflow_call:
  push:
    branches:
      - web-csr

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint:ci
      - name: Style Lint
        run: npm run stylelint

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run test

  build_test:
    needs:
      - lint
      - test
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repository
          uses: actions/checkout@main
        - name: Install dependencies
          run: npm ci
        - name: Build application
          run: npm run build