name: CI

on:
  workflow_call:


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
  build_test:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repository
          uses: actions/checkout@main
        - name: Install dependencies
          run: npm ci
        - name: Build application
          run: npm run build

  #TODO: implement tests
